sonar.projectKey=agustintamb_balanzen-frontend
sonar.organization=agustintamb
sonar.host.url=https://sonarcloud.io

sonar.sources=app,api,components,hooks,stores,providers,utils,config
sonar.tests=app,api,components,hooks,stores,providers,utils,config
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=node_modules/**,coverage/**,**/__tests__/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/__test-utils__/**,types/**,**/*.types.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
